
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DbEntity`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=ZIXIANG-PC;uid=sa;pwd=123;database=UltraDb`
//     Schema:                 ``
//     Include Views:          `True`

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace DbEntity
{
	public partial class DbEntityDB : Database
	{
		public DbEntityDB() 
			: base("DbEntity")
		{
			CommonConstruct();
		}

		public DbEntityDB(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
			DbEntityDB GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static DbEntityDB GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			else
				return new DbEntityDB();
        }

		[ThreadStatic] static DbEntityDB _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        
		[Serializable]
		public partial class Record<T> where T:class,new()
		{
			public T Copy()
			{
				//return DoubleBullet.Surmnt.FrameWork.Entity.FrameWorkBaseEntity.DeSerialize<T>(DoubleBullet.Surmnt.FrameWork.Entity.FrameWorkBaseEntity.Serialize<T>(this as T));
				return Ultra.Web.Core.Common.ObjectHelper.DeepCopy<T>(this as T);
			}
			public static DbEntityDB repo { get { return DbEntityDB.GetInstance(); } }
			public bool IsNew() { return repo.IsNew(this); }
			public object Insert() { return repo.Insert(this); }
			public int Update(IEnumerable<string> columns) { return repo.Update(this, columns); }
			public static int Update(string sql, params object[] args) { return repo.Update<T>(sql, args); }
			public static int Update(Sql sql) { return repo.Update<T>(sql); }
			public int Delete() { return repo.Delete(this); }
			public static int Delete(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Delete(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(object primaryKey) { return repo.Delete<T>(primaryKey); }
			public static bool Exists(object primaryKey) { return repo.Exists<T>(primaryKey); }
			public static T SingleOrDefault(object primaryKey) { return repo.SingleOrDefault<T>(primaryKey); }
			public static T SingleOrDefault(string sql, params object[] args) { return repo.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Sql sql) { return repo.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(string sql, params object[] args) { return repo.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Sql sql) { return repo.FirstOrDefault<T>(sql); }
			public static T Single(object primaryKey) { return repo.Single<T>(primaryKey); }
			public static T Single(string sql, params object[] args) { return repo.Single<T>(sql, args); }
			public static T Single(Sql sql) { return repo.Single<T>(sql); }
			public static T First(string sql, params object[] args) { return repo.First<T>(sql, args); }
			public static T First(Sql sql) { return repo.First<T>(sql); }
			public static List<T> Fetch(string sql, params object[] args) { return repo.Fetch<T>(sql, args); }
			public static List<T> Fetch(Sql sql) { return repo.Fetch<T>(sql); }
			public static List<T> Fetch(long page, long itemsPerPage, string sql, params object[] args) { return repo.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(long page, long itemsPerPage, Sql sql) { return repo.Fetch<T>(page, itemsPerPage, sql); }
			public static List<T> SkipTake(long skip, long take, string sql, params object[] args) { return repo.SkipTake<T>(skip, take, sql, args); }
			public static List<T> SkipTake(long skip, long take, Sql sql) { return repo.SkipTake<T>(skip, take, sql); }
			public static Page<T> Page(long page, long itemsPerPage, string sql, params object[] args) { return repo.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(long page, long itemsPerPage, Sql sql) { return repo.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(string sql, params object[] args) { return repo.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Sql sql) { return repo.Query<T>(sql); }
			
			private Dictionary<string,bool> ModifiedColumns;
			private void OnLoaded()
			{
				ModifiedColumns = new Dictionary<string,bool>();
			}
			protected void MarkColumnModified(string column_name)
			{
				if (ModifiedColumns!=null)
					ModifiedColumns[column_name]=true;
			}
			public int Update() 
			{ 
				if (ModifiedColumns==null)
					return repo.Update(this); 

				int retv = repo.Update(this, ModifiedColumns.Keys);
				ModifiedColumns.Clear();
				return retv;
			}
			public void Save() 
			{ 
				if (repo.IsNew(this))
					repo.Insert(this);
				else
					Update();
			}
		}
	}
	

    
	[TableName("t_role")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_role : DbEntityDB.Record<t_role>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("Name")]
        [Column] 
		public string Name 
		{ 
			get
			{
				return _Name;
			}
			set
			{
				_Name = value;
				MarkColumnModified("Name");
			}
		}
		string _Name;


        [System.Xml.Serialization.XmlElement("Desc")]
        [Column] 
		public string Desc 
		{ 
			get
			{
				return _Desc;
			}
			set
			{
				_Desc = value;
				MarkColumnModified("Desc");
			}
		}
		string _Desc;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_user")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_user : DbEntityDB.Record<t_user>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("UserName")]
        [Column] 
		public string UserName 
		{ 
			get
			{
				return _UserName;
			}
			set
			{
				_UserName = value;
				MarkColumnModified("UserName");
			}
		}
		string _UserName;


        [System.Xml.Serialization.XmlElement("Pwd")]
        [Column] 
		public string Pwd 
		{ 
			get
			{
				return _Pwd;
			}
			set
			{
				_Pwd = value;
				MarkColumnModified("Pwd");
			}
		}
		string _Pwd;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_roleset")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_roleset : DbEntityDB.Record<t_roleset>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("RoleName")]
        [Column] 
		public string RoleName 
		{ 
			get
			{
				return _RoleName;
			}
			set
			{
				_RoleName = value;
				MarkColumnModified("RoleName");
			}
		}
		string _RoleName;


        [System.Xml.Serialization.XmlElement("RoleId")]
        [Column] 
		public int RoleId 
		{ 
			get
			{
				return _RoleId;
			}
			set
			{
				_RoleId = value;
				MarkColumnModified("RoleId");
			}
		}
		int _RoleId;


        [System.Xml.Serialization.XmlElement("RoleSetTree")]
        [Column] 
		public string RoleSetTree 
		{ 
			get
			{
				return _RoleSetTree;
			}
			set
			{
				_RoleSetTree = value;
				MarkColumnModified("RoleSetTree");
			}
		}
		string _RoleSetTree;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_roleuser")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_roleuser : DbEntityDB.Record<t_roleuser>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("UserId")]
        [Column] 
		public int UserId 
		{ 
			get
			{
				return _UserId;
			}
			set
			{
				_UserId = value;
				MarkColumnModified("UserId");
			}
		}
		int _UserId;


        [System.Xml.Serialization.XmlElement("RoleId")]
        [Column] 
		public int RoleId 
		{ 
			get
			{
				return _RoleId;
			}
			set
			{
				_RoleId = value;
				MarkColumnModified("RoleId");
			}
		}
		int _RoleId;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_menu")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_menu : DbEntityDB.Record<t_menu>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("Version")]
        [Column] 
		public string Version 
		{ 
			get
			{
				return _Version;
			}
			set
			{
				_Version = value;
				MarkColumnModified("Version");
			}
		}
		string _Version;


        [System.Xml.Serialization.XmlElement("MenuXml")]
        [Column] 
		public string MenuXml 
		{ 
			get
			{
				return _MenuXml;
			}
			set
			{
				_MenuXml = value;
				MarkColumnModified("MenuXml");
			}
		}
		string _MenuXml;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_mac")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_mac : DbEntityDB.Record<t_mac>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("Mac")]
        [Column] 
		public string Mac 
		{ 
			get
			{
				return _Mac;
			}
			set
			{
				_Mac = value;
				MarkColumnModified("Mac");
			}
		}
		string _Mac;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_loginfail")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_loginfail : DbEntityDB.Record<t_loginfail>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("UserName")]
        [Column] 
		public string UserName 
		{ 
			get
			{
				return _UserName;
			}
			set
			{
				_UserName = value;
				MarkColumnModified("UserName");
			}
		}
		string _UserName;


        [System.Xml.Serialization.XmlElement("LoginMAC")]
        [Column] 
		public string LoginMAC 
		{ 
			get
			{
				return _LoginMAC;
			}
			set
			{
				_LoginMAC = value;
				MarkColumnModified("LoginMAC");
			}
		}
		string _LoginMAC;


        [System.Xml.Serialization.XmlElement("ExternalIP")]
        [Column] 
		public string ExternalIP 
		{ 
			get
			{
				return _ExternalIP;
			}
			set
			{
				_ExternalIP = value;
				MarkColumnModified("ExternalIP");
			}
		}
		string _ExternalIP;


        [System.Xml.Serialization.XmlElement("LocalIP")]
        [Column] 
		public string LocalIP 
		{ 
			get
			{
				return _LocalIP;
			}
			set
			{
				_LocalIP = value;
				MarkColumnModified("LocalIP");
			}
		}
		string _LocalIP;


        [System.Xml.Serialization.XmlElement("LoginTime")]
        [Column] 
		public DateTime LoginTime 
		{ 
			get
			{
				return _LoginTime;
			}
			set
			{
				_LoginTime = value;
				MarkColumnModified("LoginTime");
			}
		}
		DateTime _LoginTime;


        [System.Xml.Serialization.XmlElement("LastUpdateTime")]
        [Column] 
		public DateTime LastUpdateTime 
		{ 
			get
			{
				return _LastUpdateTime;
			}
			set
			{
				_LastUpdateTime = value;
				MarkColumnModified("LastUpdateTime");
			}
		}
		DateTime _LastUpdateTime;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_logincur")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_logincur : DbEntityDB.Record<t_logincur>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("UserName")]
        [Column] 
		public string UserName 
		{ 
			get
			{
				return _UserName;
			}
			set
			{
				_UserName = value;
				MarkColumnModified("UserName");
			}
		}
		string _UserName;


        [System.Xml.Serialization.XmlElement("LoginMAC")]
        [Column] 
		public string LoginMAC 
		{ 
			get
			{
				return _LoginMAC;
			}
			set
			{
				_LoginMAC = value;
				MarkColumnModified("LoginMAC");
			}
		}
		string _LoginMAC;


        [System.Xml.Serialization.XmlElement("ExternalIP")]
        [Column] 
		public string ExternalIP 
		{ 
			get
			{
				return _ExternalIP;
			}
			set
			{
				_ExternalIP = value;
				MarkColumnModified("ExternalIP");
			}
		}
		string _ExternalIP;


        [System.Xml.Serialization.XmlElement("LocalIP")]
        [Column] 
		public string LocalIP 
		{ 
			get
			{
				return _LocalIP;
			}
			set
			{
				_LocalIP = value;
				MarkColumnModified("LocalIP");
			}
		}
		string _LocalIP;


        [System.Xml.Serialization.XmlElement("LoginTime")]
        [Column] 
		public DateTime LoginTime 
		{ 
			get
			{
				return _LoginTime;
			}
			set
			{
				_LoginTime = value;
				MarkColumnModified("LoginTime");
			}
		}
		DateTime _LoginTime;


        [System.Xml.Serialization.XmlElement("LastUpdateTime")]
        [Column] 
		public DateTime LastUpdateTime 
		{ 
			get
			{
				return _LastUpdateTime;
			}
			set
			{
				_LastUpdateTime = value;
				MarkColumnModified("LastUpdateTime");
			}
		}
		DateTime _LastUpdateTime;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_forcedoffline")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_forcedoffline : DbEntityDB.Record<t_forcedoffline>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("LoginMAC")]
        [Column] 
		public string LoginMAC 
		{ 
			get
			{
				return _LoginMAC;
			}
			set
			{
				_LoginMAC = value;
				MarkColumnModified("LoginMAC");
			}
		}
		string _LoginMAC;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
}


